import { describe, expect, it } from "vitest";
import { sessionUserSchema } from "./auth.ts";

describe("sessionUserSchema", () => {
	it("accepts user IDs generated by older Better Auth versions", () => {
		const result = sessionUserSchema.safeParse({
			id: "a".repeat(32),
			email: "admin@test.app",
			name: "Admin",
			role: "admin",
		});

		expect(result.success).toBe(true);
	});

	it("continues to accept UUID user IDs", () => {
		const result = sessionUserSchema.safeParse({
			id: "550e8400-e29b-41d4-a716-446655440000",
			email: "admin@test.app",
			name: "Admin",
			role: "admin",
		});

		expect(result.success).toBe(true);
	});
});
